//! Minimal test plugin binary implementing the yard plugin protocol.
//!
//! This binary is compiled as a standalone Cargo project (NOT a workspace
//! member) and spawned by integration tests to validate the plugin host
//! module's end-to-end behavior.
//!
//! The `TEST_PLUGIN_MODE` env var controls failure mode simulation:
//! - unset / "normal": standard protocol flow
//! - "bad_version": handshake with protocol_version 999
//! - "crash": handshake then exit(1) before response
//! - "hang": handshake then sleep 600s (timeout testing)
//! - "no_handshake": skip handshake, try to read stdin immediately

use std::io::{self, BufRead, Write};

fn main() {
    let mode = std::env::var("TEST_PLUGIN_MODE").unwrap_or_else(|_| "normal".to_string());

    match mode.as_str() {
        "no_handshake" => {
            // Skip handshake -- read stdin immediately (will fail protocol)
            let stdin = io::stdin();
            let mut line = String::new();
            let _ = stdin.lock().read_line(&mut line);
            // Write a response without handshake
            let resp = serde_json::json!({"type": "response", "errors": []});
            println!("{}", resp);
        }
        "bad_version" => {
            // Handshake with wrong protocol version
            let handshake = serde_json::json!({
                "protocol_version": 999,
                "name": "test-plugin",
                "version": "0.1.0",
                "capabilities": ["validate", "codegen", "deploy", "destroy", "verify", "schema"]
            });
            println!("{}", handshake);
            io::stdout().flush().unwrap();

            // Read request (host may kill us before we get here)
            let stdin = io::stdin();
            let mut line = String::new();
            let _ = stdin.lock().read_line(&mut line);
        }
        "crash" => {
            // Valid handshake then crash (non-zero exit)
            let handshake = serde_json::json!({
                "protocol_version": 1,
                "name": "test-plugin",
                "version": "0.1.0",
                "capabilities": ["validate", "codegen", "deploy", "destroy", "verify", "schema"]
            });
            println!("{}", handshake);
            io::stdout().flush().unwrap();

            // Read request
            let stdin = io::stdin();
            let mut line = String::new();
            let _ = stdin.lock().read_line(&mut line);

            // Exit with non-zero code without sending response
            std::process::exit(1);
        }
        "hang" => {
            // Valid handshake then hang (for timeout testing)
            let handshake = serde_json::json!({
                "protocol_version": 1,
                "name": "test-plugin",
                "version": "0.1.0",
                "capabilities": ["validate", "codegen", "deploy", "destroy", "verify", "schema"]
            });
            println!("{}", handshake);
            io::stdout().flush().unwrap();

            // Read request
            let stdin = io::stdin();
            let mut line = String::new();
            let _ = stdin.lock().read_line(&mut line);

            // Sleep for a very long time (will be killed by timeout)
            std::thread::sleep(std::time::Duration::from_secs(600));
        }
        _ => {
            // Normal mode: full protocol flow
            run_normal();
        }
    }
}

fn run_normal() {
    // Step 1: Write handshake line
    let handshake = serde_json::json!({
        "protocol_version": 1,
        "name": "test-plugin",
        "version": "0.1.0",
        "capabilities": ["validate", "codegen", "deploy", "destroy", "verify", "schema"]
    });
    println!("{}", handshake);
    io::stdout().flush().unwrap();

    // Step 2: Read request from stdin
    let stdin = io::stdin();
    let mut line = String::new();
    stdin.lock().read_line(&mut line).unwrap();

    let request: serde_json::Value = serde_json::from_str(line.trim()).unwrap();
    let operation = request["operation"].as_str().unwrap();

    // Step 3: Dispatch based on operation
    let response = match operation {
        "validate" => {
            serde_json::json!({"type": "response", "errors": []})
        }
        "codegen" => {
            serde_json::json!({"type": "response", "script": "# generated by test-plugin\nprint('hello')"})
        }
        "deploy" => {
            // Emit a progress line first (PROTO-03)
            let progress = serde_json::json!({
                "type": "progress",
                "message": "deploying resources...",
                "percent": 50
            });
            println!("{}", progress);
            io::stdout().flush().unwrap();

            serde_json::json!({
                "type": "response",
                "resources": [{
                    "type": "TestResource",
                    "id": "test-123",
                    "provider": "test-plugin"
                }]
            })
        }
        "destroy" => {
            serde_json::json!({"type": "response"})
        }
        "verify" => {
            serde_json::json!({
                "type": "response",
                "statuses": [{
                    "resource": {
                        "type": "TestResource",
                        "id": "test-123",
                        "provider": "test-plugin"
                    },
                    "exists": true
                }]
            })
        }
        "schema" => {
            serde_json::json!({
                "type": "response",
                "fields": [{
                    "name": "region",
                    "field_type": "string",
                    "required": true,
                    "description": "AWS region"
                }]
            })
        }
        unknown => {
            serde_json::json!({"type": "error", "message": format!("unknown operation: {}", unknown)})
        }
    };

    // Step 4: Write response line and flush
    println!("{}", response);
    io::stdout().flush().unwrap();
}
