use anyhow::{Context as AnyhowContext, Result};
use tera::{Context, Tera};
use yard_structs::JobDefinition;

pub fn generate_python_script(job_name: &str, job_def: &JobDefinition) -> Result<String> {
    let mut tera = Tera::default();

    // 1. The "Master Template" - This is your base Glue Spark script
    let template_content = r#"
# Generated by YARD for job: {{ job_name }}

import sys
import logging
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job


MSG_FORMAT = '%(asctime)s %(levelname)s %(name)s: %(message)s'
logging.basicConfig(format=MSG_FORMAT, level=logging.INFO)
logger = logging.getLogger("yard")


args = getResolvedOptions(sys.argv, ['JOB_NAME'])
sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args['JOB_NAME'], args)

# --- JOB CONFIG ---
CONFIG = {{ config_json }}

def run():
    try:
        logger.info(f"Processing job type: {{ job_type }}")

        # --- TASK SPECIFIC LOGIC ---
        # In a real scenario, we'd branch logic here based on {{ job_type }}
        # For now, we just log the config we're working with
        for key, value in CONFIG.items():
            logger.info(f"Config Param - {key}: {value}")

        logger.info("Task completed successfully")

    except Exception as e:
        logger.error(f"Job failed with error: {str(e)}")
        raise e

if __name__ == "__main__":
    run()
    job.commit()
    logger.info("Glue Job committed and finished")
"#;

    tera.add_raw_template("glue_script", template_content)?;

    // 2. Prepare the context (Inject the YAML config)
    let mut context = Context::new();
    context.insert("job_name", job_name);
    context.insert("job_type", &job_def.job_type);

    // We pass the whole config as a JSON string so Python can parse it easily
    let config_json = serde_json::to_string_pretty(&job_def.config)?;
    context.insert("config_json", &config_json);

    // 3. Render
    let rendered = tera
        .render("glue_script", &context)
        .context("Failed to render Python template")?;

    Ok(rendered)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn glue_job() -> JobDefinition {
        JobDefinition {
            job_type: "glue".to_string(),
            config: json!({
                "type": "glue",
                "script_name": "my_etl",
                "role_arn": "arn:aws:iam::123:role/glue"
            }),
        }
    }

    #[test]
    fn generates_valid_script() {
        let script = generate_python_script("test_job", &glue_job()).unwrap();
        assert!(script.contains("Generated by YARD for job: test_job"));
    }

    #[test]
    fn embeds_config_as_json() {
        let script = generate_python_script("test_job", &glue_job()).unwrap();
        assert!(script.contains("my_etl"));
        assert!(script.contains("arn:aws:iam::123:role/glue"));
    }

    #[test]
    fn includes_glue_boilerplate() {
        let script = generate_python_script("test_job", &glue_job()).unwrap();
        assert!(script.contains("from awsglue.utils import getResolvedOptions"));
        assert!(script.contains("GlueContext"));
        assert!(script.contains("job.init"));
        assert!(script.contains("job.commit()"));
    }

    #[test]
    fn includes_job_type_in_logging() {
        let script = generate_python_script("test_job", &glue_job()).unwrap();
        assert!(script.contains("Processing job type: glue"));
    }

    #[test]
    fn different_jobs_produce_different_scripts() {
        let a = generate_python_script("job_a", &glue_job()).unwrap();
        let b = generate_python_script("job_b", &glue_job()).unwrap();
        assert_ne!(a, b);
        assert!(a.contains("job_a"));
        assert!(b.contains("job_b"));
    }
}
