use anyhow::{Context as AnyhowContext, Result, anyhow};
use tera::{Context, Tera};
use yard_structs::{Import, JobDefinition};

const GLUE_TEMPLATE: &str = include_str!("templates/glue.py.tera");

fn render_import(import: &Import) -> String {
    match &import.from {
        Some(module) => format!("from {} import {}", module, import.name),
        None => format!("import {}", import.name),
    }
}

fn render_imports(imports: &[Import]) -> String {
    imports.iter().map(render_import).collect::<Vec<_>>().join("\n")
}

/// Indent a body string so it sits correctly inside `def run():`.
fn indent_body(body: &str) -> String {
    body.lines()
        .map(|line| {
            if line.trim().is_empty() {
                String::new()
            } else {
                format!("    {}", line)
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

pub fn generate_python_script(job_name: &str, job_def: &JobDefinition) -> Result<String> {
    let template = match job_def.job_type.as_str() {
        "glue" => GLUE_TEMPLATE,
        other => return Err(anyhow!("Unsupported job type: {}", other)),
    };

    let mut tera = Tera::default();
    tera.add_raw_template("script", template)?;

    let mut context = Context::new();
    context.insert("job_name", job_name);
    context.insert("job_type", &job_def.job_type);
    context.insert("imports_block", &render_imports(&job_def.imports));

    match &job_def.body {
        Some(body) => context.insert("body", &indent_body(body)),
        None => context.insert("body", &""),
    }

    let rendered = tera
        .render("script", &context)
        .context("Failed to render Python template")?;

    Ok(rendered)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn glue_job(imports: Vec<Import>, body: Option<String>) -> JobDefinition {
        JobDefinition {
            job_type: "glue".to_string(),
            imports,
            body,
            config: json!({"type": "glue", "script_name": "my_etl"}),
        }
    }

    // --- Routing ---

    #[test]
    fn unsupported_job_type_errors() {
        let job = JobDefinition {
            job_type: "unknown".to_string(),
            imports: vec![],
            body: None,
            config: json!({}),
        };
        let result = generate_python_script("test", &job);
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("Unsupported job type"));
    }

    // --- Header ---

    #[test]
    fn generates_header() {
        let script = generate_python_script("test_job", &glue_job(vec![], None)).unwrap();
        assert!(script.contains("Generated by YARD for job: test_job"));
    }

    // --- Imports ---

    #[test]
    fn simple_import() {
        let job = glue_job(vec![
            Import { name: "sys".to_string(), from: None },
        ], None);
        let script = generate_python_script("test_job", &job).unwrap();
        assert!(script.contains("import sys"));
    }

    #[test]
    fn from_import() {
        let job = glue_job(vec![
            Import { name: "Job".to_string(), from: Some("awsglue.job".to_string()) },
        ], None);
        let script = generate_python_script("test_job", &job).unwrap();
        assert!(script.contains("from awsglue.job import Job"));
    }

    #[test]
    fn multiple_imports() {
        let job = glue_job(vec![
            Import { name: "sys".to_string(), from: None },
            Import { name: "logging".to_string(), from: None },
            Import { name: "SparkContext".to_string(), from: Some("pyspark.context".to_string()) },
        ], None);
        let script = generate_python_script("test_job", &job).unwrap();
        assert!(script.contains("import sys"));
        assert!(script.contains("import logging"));
        assert!(script.contains("from pyspark.context import SparkContext"));
    }

    // --- Glue setup/teardown ---

    #[test]
    fn glue_setup() {
        let script = generate_python_script("test_job", &glue_job(vec![], None)).unwrap();
        // Template-owned imports
        assert!(script.contains("import sys"));
        assert!(script.contains("from awsglue.utils import getResolvedOptions"));
        assert!(script.contains("from pyspark.context import SparkContext"));
        assert!(script.contains("from awsglue.context import GlueContext"));
        assert!(script.contains("from awsglue.job import Job"));
        // Setup code
        assert!(script.contains("SparkContext()"));
        assert!(script.contains("GlueContext(sc)"));
        assert!(script.contains("job.init"));
    }

    #[test]
    fn glue_teardown() {
        let script = generate_python_script("test_job", &glue_job(vec![], None)).unwrap();
        assert!(script.contains("job.commit()"));
    }

    // --- Body ---

    #[test]
    fn default_body_is_pass() {
        let script = generate_python_script("test_job", &glue_job(vec![], None)).unwrap();
        assert!(script.contains("    pass"));
    }

    #[test]
    fn body_override() {
        let body = "logger.info(\"hello\")\ndf = spark.read.parquet(\"s3://bucket\")".to_string();
        let script = generate_python_script("test_job", &glue_job(vec![], Some(body))).unwrap();
        assert!(script.contains("    logger.info(\"hello\")"));
        assert!(script.contains("    df = spark.read.parquet(\"s3://bucket\")"));
        assert!(!script.contains("    pass"));
    }

    // --- Differentiation ---

    #[test]
    fn different_jobs_produce_different_scripts() {
        let job = glue_job(vec![], None);
        let a = generate_python_script("job_a", &job).unwrap();
        let b = generate_python_script("job_b", &job).unwrap();
        assert_ne!(a, b);
    }
}
