use anyhow::{Context as AnyhowContext, Result};
use tera::{Context, Tera};
use yard_structs::JobDefinition;

pub fn generate_python_script(job_name: &str, job_def: &JobDefinition) -> Result<String> {
    let mut tera = Tera::default();

    // 1. The "Master Template" - This is your base Glue Spark script
    let template_content = r#"
# Generated by YARD for job: {{ job_name }}

import sys
import logging
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job


MSG_FORMAT = '%(asctime)s %(levelname)s %(name)s: %(message)s'
logging.basicConfig(format=MSG_FORMAT, level=logging.INFO)
logger = logging.getLogger("yard")


args = getResolvedOptions(sys.argv, ['JOB_NAME'])
sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args['JOB_NAME'], args)

# --- JOB CONFIG ---
CONFIG = {{ config_json }}

def run():
    try:
        logger.info(f"Processing job type: {{ job_type }}")

        # --- TASK SPECIFIC LOGIC ---
        # In a real scenario, we'd branch logic here based on {{ job_type }}
        # For now, we just log the config we're working with
        for key, value in CONFIG.items():
            logger.info(f"Config Param - {key}: {value}")

        logger.info("Task completed successfully")

    except Exception as e:
        logger.error(f"Job failed with error: {str(e)}")
        raise e

if __name__ == "__main__":
    run()
    job.commit()
    logger.info("Glue Job committed and finished")
"#;

    tera.add_raw_template("glue_script", template_content)?;

    // 2. Prepare the context (Inject the YAML config)
    let mut context = Context::new();
    context.insert("job_name", job_name);
    context.insert("job_type", &job_def.job_type);

    // We pass the whole config as a JSON string so Python can parse it easily
    let config_json = serde_json::to_string_pretty(&job_def.config)?;
    context.insert("config_json", &config_json);

    // 3. Render
    let rendered = tera
        .render("glue_script", &context)
        .context("Failed to render Python template")?;

    Ok(rendered)
}
