#![allow(clippy::unwrap_used, clippy::expect_used)]
//! Integration tests for the plugin host module.
//!
//! These tests compile and spawn the `test_plugin` binary to exercise
//! the full plugin host lifecycle: handshake, all 6 operations, progress
//! lines, timeout, crash handling, and version rejection.
//!
//! The test_plugin binary is a standalone Cargo project at
//! `yard-core/tests/test_plugin/` that implements the yard plugin protocol
//! without depending on yard-structs.

use std::path::PathBuf;
use std::sync::OnceLock;

use serde_json::json;
use yard_core::plugin_host::{PluginHostConfig, PluginProvider, PluginSpawner};
use yard_core::providers::Provider;

static TEST_PLUGIN_PATH: OnceLock<PathBuf> = OnceLock::new();

/// Build the test plugin binary once per test run and return its path.
fn build_test_plugin() -> PathBuf {
    TEST_PLUGIN_PATH
        .get_or_init(|| {
            let manifest_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .join("tests/test_plugin/Cargo.toml");

            let output = std::process::Command::new("cargo")
                .arg("build")
                .arg("--manifest-path")
                .arg(&manifest_path)
                .output()
                .expect("failed to run cargo build for test plugin");

            assert!(
                output.status.success(),
                "test plugin build failed:\n{}",
                String::from_utf8_lossy(&output.stderr)
            );

            let binary = manifest_path
                .parent()
                .unwrap()
                .join("target/debug/test-plugin");
            assert!(
                binary.exists(),
                "test plugin binary not found at {}",
                binary.display()
            );

            binary
        })
        .clone()
}

/// Create a PluginSpawner pointed at the test binary.
///
/// If `mode` is Some, sets TEST_PLUGIN_MODE in the child process env.
fn make_spawner(mode: Option<&str>) -> PluginSpawner {
    let binary = build_test_plugin();
    let config = PluginHostConfig {
        plugins_dir: PathBuf::from("/tmp/yard-test-plugins"),
        timeout_secs: 5,
        lock_file_path: None,
    };

    let mut spawner = PluginSpawner::new(binary, "test-plugin".to_string(), config);
    if let Some(m) = mode {
        spawner = spawner.with_env("TEST_PLUGIN_MODE", m);
    }
    spawner
}

/// Create a PluginSpawner with a custom timeout.
fn make_spawner_with_timeout(mode: Option<&str>, timeout_secs: u64) -> PluginSpawner {
    let binary = build_test_plugin();
    let config = PluginHostConfig {
        plugins_dir: PathBuf::from("/tmp/yard-test-plugins"),
        timeout_secs,
        lock_file_path: None,
    };

    let mut spawner = PluginSpawner::new(binary, "test-plugin".to_string(), config);
    if let Some(m) = mode {
        spawner = spawner.with_env("TEST_PLUGIN_MODE", m);
    }
    spawner
}

// ---- Happy path tests (one per operation) ----

#[tokio::test]
async fn test_validate_operation_returns_empty_errors() {
    let spawner = make_spawner(None);
    let result = spawner
        .call_validate("test-job", &json!({"type": "glue"}))
        .await;

    let errors = result.unwrap();
    assert!(errors.is_empty(), "expected empty errors, got: {:?}", errors);
}

#[tokio::test]
async fn test_codegen_operation_returns_generated_script() {
    let spawner = make_spawner(None);
    let result = spawner
        .call_codegen("test-job", &json!({"type": "glue"}))
        .await;

    let script = result.unwrap();
    assert!(script.is_some(), "expected Some(script)");
    let content = script.unwrap();
    assert!(
        content.contains("generated by test-plugin"),
        "expected test-plugin script, got: {content}"
    );
    assert!(content.contains("print('hello')"));
}

#[tokio::test]
async fn test_deploy_operation_returns_resources() {
    let spawner = make_spawner(None);
    let result = spawner
        .call_deploy("test-job", "print('hello')", &json!({"type": "glue"}))
        .await;

    let resources = result.unwrap();
    assert_eq!(resources.len(), 1);
    assert_eq!(resources[0].r#type, "TestResource");
    assert_eq!(resources[0].id, "test-123");
    assert_eq!(resources[0].provider, "test-plugin");
}

#[tokio::test]
async fn test_destroy_operation_succeeds() {
    let spawner = make_spawner(None);
    let resources = vec![yard_structs::Resource {
        r#type: "TestResource".to_string(),
        id: "test-123".to_string(),
        provider: "test-plugin".to_string(),
    }];

    let result = spawner.call_destroy("test-job", &resources).await;
    assert!(result.is_ok(), "destroy should succeed: {:?}", result.err());
}

#[tokio::test]
async fn test_verify_operation_returns_statuses() {
    let spawner = make_spawner(None);
    let resources = vec![yard_structs::Resource {
        r#type: "TestResource".to_string(),
        id: "test-123".to_string(),
        provider: "test-plugin".to_string(),
    }];

    let result = spawner.call_verify("test-job", &resources).await;
    let statuses = result.unwrap();
    assert_eq!(statuses.len(), 1);
    assert!(statuses[0].exists, "resource should exist");
    assert_eq!(statuses[0].resource.id, "test-123");
}

#[tokio::test]
async fn test_schema_operation_returns_field_descriptors() {
    let spawner = make_spawner(None);
    let result = spawner.call_schema().await;

    let fields = result.unwrap();
    assert_eq!(fields.len(), 1);
    assert_eq!(fields[0].name, "region");
    assert_eq!(fields[0].field_type, "string");
    assert!(fields[0].required);
    assert_eq!(fields[0].description, "AWS region");
}

// ---- Protocol tests ----

#[tokio::test]
async fn test_progress_lines_received_during_deploy() {
    let spawner = make_spawner(None);
    // Deploy operation emits a progress line. The spawner's typed methods
    // use eprintln for progress, but we can verify the operation succeeds
    // (which means the progress line was parsed and not treated as the
    // response). If progress parsing were broken, the response would be
    // the progress JSON and deserialization would fail.
    let result = spawner
        .call_deploy("test-job", "print('hello')", &json!({"type": "glue"}))
        .await;

    // Success implies the progress line was correctly parsed and skipped
    let resources = result.unwrap();
    assert_eq!(resources.len(), 1, "deploy should return one resource");
}

#[tokio::test]
async fn test_version_mismatch_rejected() {
    let spawner = make_spawner(Some("bad_version"));
    let result = spawner
        .call_validate("test-job", &json!({"type": "glue"}))
        .await;

    assert!(result.is_err(), "bad version should be rejected");
    let err_msg = format!("{:#}", result.unwrap_err());
    assert!(
        err_msg.contains("version") && err_msg.contains("mismatch"),
        "error should mention version mismatch, got: {err_msg}"
    );
}

#[tokio::test]
async fn test_plugin_crash_returns_error_with_plugin_name() {
    let spawner = make_spawner(Some("crash"));
    let result = spawner
        .call_validate("test-job", &json!({"type": "glue"}))
        .await;

    assert!(result.is_err(), "crash should produce an error");
    let err_msg = format!("{:#}", result.unwrap_err());
    assert!(
        err_msg.contains("test-plugin"),
        "error should include plugin name, got: {err_msg}"
    );
}

#[tokio::test]
async fn test_timeout_kills_hung_process() {
    let spawner = make_spawner_with_timeout(Some("hang"), 1);
    let result = spawner
        .call_validate("test-job", &json!({"type": "glue"}))
        .await;

    assert!(result.is_err(), "hung plugin should time out");
    let err_msg = format!("{:#}", result.unwrap_err());
    assert!(
        err_msg.contains("timed out"),
        "error should mention timeout, got: {err_msg}"
    );
}

#[tokio::test]
async fn test_missing_handshake_returns_error() {
    let spawner = make_spawner(Some("no_handshake"));
    let result = spawner
        .call_validate("test-job", &json!({"type": "glue"}))
        .await;

    assert!(result.is_err(), "missing handshake should produce an error");
}

// ---- Provider trait test ----

#[tokio::test]
async fn test_plugin_provider_implements_provider_trait() {
    let binary = build_test_plugin();
    let config = PluginHostConfig {
        plugins_dir: PathBuf::from("/tmp/yard-test-plugins"),
        timeout_secs: 5,
        lock_file_path: None,
    };

    let provider = PluginProvider::from_binary(
        binary,
        "test-plugin".to_string(),
        config,
    );

    // Verify object safety -- store as Box<dyn Provider>
    let boxed: Box<dyn Provider> = Box::new(provider);

    // Call deploy through the Provider trait interface
    let result = boxed
        .deploy("test-job", "print('hello')", &json!({"type": "glue"}))
        .await;

    let resources = result.unwrap();
    assert_eq!(resources.len(), 1);
    assert_eq!(resources[0].r#type, "TestResource");
    assert_eq!(resources[0].id, "test-123");
}
