#![allow(clippy::unwrap_used, clippy::expect_used)]
//! Integration tests for the plugin host module.
//!
//! These tests compile and spawn the `test_plugin` binary to exercise
//! the full plugin host lifecycle: handshake, all 6 operations, progress
//! lines, timeout, crash handling, and version rejection.
//!
//! The test_plugin binary is a standalone Cargo project at
//! `yard-core/tests/test_plugin/` that implements the yard plugin protocol
//! without depending on yard-structs.

use std::path::PathBuf;
use std::sync::OnceLock;

use serde_json::json;
use yard_core::plugin_host::{PluginHostConfig, PluginProvider, PluginSpawner};
use yard_core::providers::Provider;

// Imports for download/cache integration tests
use yard_core::plugin_host::download::{ensure_plugin_cached, update_lock_file};
use yard_core::plugin_host::spawner::{LockFile, platform_key};

static TEST_PLUGIN_PATH: OnceLock<PathBuf> = OnceLock::new();

/// Build the test plugin binary once per test run and return its path.
fn build_test_plugin() -> PathBuf {
    TEST_PLUGIN_PATH
        .get_or_init(|| {
            let manifest_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .join("tests/test_plugin/Cargo.toml");

            let output = std::process::Command::new("cargo")
                .arg("build")
                .arg("--manifest-path")
                .arg(&manifest_path)
                .output()
                .expect("failed to run cargo build for test plugin");

            assert!(
                output.status.success(),
                "test plugin build failed:\n{}",
                String::from_utf8_lossy(&output.stderr)
            );

            let binary = manifest_path
                .parent()
                .unwrap()
                .join("target/debug/test-plugin");
            assert!(
                binary.exists(),
                "test plugin binary not found at {}",
                binary.display()
            );

            binary
        })
        .clone()
}

/// Create a PluginSpawner pointed at the test binary.
///
/// If `mode` is Some, sets TEST_PLUGIN_MODE in the child process env.
fn make_spawner(mode: Option<&str>) -> PluginSpawner {
    let binary = build_test_plugin();
    let config = PluginHostConfig {
        plugins_dir: PathBuf::from("/tmp/yard-test-plugins"),
        timeout_secs: 5,
        lock_file_path: None,
    };

    let mut spawner = PluginSpawner::new(binary, "test-plugin".to_string(), config);
    if let Some(m) = mode {
        spawner = spawner.with_env("TEST_PLUGIN_MODE", m);
    }
    spawner
}

/// Create a PluginSpawner with a custom timeout.
fn make_spawner_with_timeout(mode: Option<&str>, timeout_secs: u64) -> PluginSpawner {
    let binary = build_test_plugin();
    let config = PluginHostConfig {
        plugins_dir: PathBuf::from("/tmp/yard-test-plugins"),
        timeout_secs,
        lock_file_path: None,
    };

    let mut spawner = PluginSpawner::new(binary, "test-plugin".to_string(), config);
    if let Some(m) = mode {
        spawner = spawner.with_env("TEST_PLUGIN_MODE", m);
    }
    spawner
}

// ---- Happy path tests (one per operation) ----

#[tokio::test]
async fn test_validate_operation_returns_empty_errors() {
    let spawner = make_spawner(None);
    let result = spawner
        .call_validate("test-job", &json!({"type": "glue"}))
        .await;

    let errors = result.unwrap();
    assert!(errors.is_empty(), "expected empty errors, got: {:?}", errors);
}

#[tokio::test]
async fn test_codegen_operation_returns_generated_script() {
    let spawner = make_spawner(None);
    let result = spawner
        .call_codegen("test-job", &json!({"type": "glue"}))
        .await;

    let script = result.unwrap();
    assert!(script.is_some(), "expected Some(script)");
    let content = script.unwrap();
    assert!(
        content.contains("generated by test-plugin"),
        "expected test-plugin script, got: {content}"
    );
    assert!(content.contains("print('hello')"));
}

#[tokio::test]
async fn test_deploy_operation_returns_resources() {
    let spawner = make_spawner(None);
    let result = spawner
        .call_deploy("test-job", "print('hello')", &json!({"type": "glue"}))
        .await;

    let resources = result.unwrap();
    assert_eq!(resources.len(), 1);
    assert_eq!(resources[0].r#type, "TestResource");
    assert_eq!(resources[0].id, "test-123");
    assert_eq!(resources[0].provider, "test-plugin");
}

#[tokio::test]
async fn test_destroy_operation_succeeds() {
    let spawner = make_spawner(None);
    let resources = vec![yard_structs::Resource {
        r#type: "TestResource".to_string(),
        id: "test-123".to_string(),
        provider: "test-plugin".to_string(),
    }];

    let result = spawner.call_destroy("test-job", &resources).await;
    assert!(result.is_ok(), "destroy should succeed: {:?}", result.err());
}

#[tokio::test]
async fn test_verify_operation_returns_statuses() {
    let spawner = make_spawner(None);
    let resources = vec![yard_structs::Resource {
        r#type: "TestResource".to_string(),
        id: "test-123".to_string(),
        provider: "test-plugin".to_string(),
    }];

    let result = spawner.call_verify("test-job", &resources).await;
    let statuses = result.unwrap();
    assert_eq!(statuses.len(), 1);
    assert!(statuses[0].exists, "resource should exist");
    assert_eq!(statuses[0].resource.id, "test-123");
}

#[tokio::test]
async fn test_schema_operation_returns_field_descriptors() {
    let spawner = make_spawner(None);
    let result = spawner.call_schema().await;

    let fields = result.unwrap();
    assert_eq!(fields.len(), 1);
    assert_eq!(fields[0].name, "region");
    assert_eq!(fields[0].field_type, "string");
    assert!(fields[0].required);
    assert_eq!(fields[0].description, "AWS region");
}

// ---- Protocol tests ----

#[tokio::test]
async fn test_progress_lines_received_during_deploy() {
    let spawner = make_spawner(None);
    // Deploy operation emits a progress line. The spawner's typed methods
    // use eprintln for progress, but we can verify the operation succeeds
    // (which means the progress line was parsed and not treated as the
    // response). If progress parsing were broken, the response would be
    // the progress JSON and deserialization would fail.
    let result = spawner
        .call_deploy("test-job", "print('hello')", &json!({"type": "glue"}))
        .await;

    // Success implies the progress line was correctly parsed and skipped
    let resources = result.unwrap();
    assert_eq!(resources.len(), 1, "deploy should return one resource");
}

#[tokio::test]
async fn test_version_mismatch_rejected() {
    let spawner = make_spawner(Some("bad_version"));
    let result = spawner
        .call_validate("test-job", &json!({"type": "glue"}))
        .await;

    assert!(result.is_err(), "bad version should be rejected");
    let err_msg = format!("{:#}", result.unwrap_err());
    assert!(
        err_msg.contains("version") && err_msg.contains("mismatch"),
        "error should mention version mismatch, got: {err_msg}"
    );
}

#[tokio::test]
async fn test_plugin_crash_returns_error_with_plugin_name() {
    let spawner = make_spawner(Some("crash"));
    let result = spawner
        .call_validate("test-job", &json!({"type": "glue"}))
        .await;

    assert!(result.is_err(), "crash should produce an error");
    let err_msg = format!("{:#}", result.unwrap_err());
    assert!(
        err_msg.contains("test-plugin"),
        "error should include plugin name, got: {err_msg}"
    );
}

#[tokio::test]
async fn test_timeout_kills_hung_process() {
    let spawner = make_spawner_with_timeout(Some("hang"), 1);
    let result = spawner
        .call_validate("test-job", &json!({"type": "glue"}))
        .await;

    assert!(result.is_err(), "hung plugin should time out");
    let err_msg = format!("{:#}", result.unwrap_err());
    assert!(
        err_msg.contains("timed out"),
        "error should mention timeout, got: {err_msg}"
    );
}

#[tokio::test]
async fn test_missing_handshake_returns_error() {
    let spawner = make_spawner(Some("no_handshake"));
    let result = spawner
        .call_validate("test-job", &json!({"type": "glue"}))
        .await;

    assert!(result.is_err(), "missing handshake should produce an error");
}

// ---- Provider trait test ----

#[tokio::test]
async fn test_plugin_provider_implements_provider_trait() {
    let binary = build_test_plugin();
    let config = PluginHostConfig {
        plugins_dir: PathBuf::from("/tmp/yard-test-plugins"),
        timeout_secs: 5,
        lock_file_path: None,
    };

    let provider = PluginProvider::from_binary(
        binary,
        "test-plugin".to_string(),
        config,
    );

    // Verify object safety -- store as Box<dyn Provider>
    let boxed: Box<dyn Provider> = Box::new(provider);

    // Call deploy through the Provider trait interface
    let result = boxed
        .deploy("test-job", "print('hello')", &json!({"type": "glue"}))
        .await;

    let resources = result.unwrap();
    assert_eq!(resources.len(), 1);
    assert_eq!(resources[0].r#type, "TestResource");
    assert_eq!(resources[0].id, "test-123");
}

// ---- Download / cache / lock-file integration tests ----

/// Return the path to the compiled test plugin binary for use as a
/// stand-in plugin binary in download/cache tests.
fn test_plugin_binary_path() -> PathBuf {
    build_test_plugin()
}

/// Helper: spin up a minimal HTTP server on an OS-assigned port that
/// serves `body` bytes on every GET request. Returns
/// `(addr, JoinHandle)`. The server runs until the handle is aborted.
fn spawn_http_server(body: Vec<u8>) -> (std::net::SocketAddr, tokio::task::JoinHandle<()>) {
    use tokio::io::AsyncWriteExt;

    let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
    let addr = listener.local_addr().unwrap();
    listener.set_nonblocking(true).unwrap();
    let tokio_listener = tokio::net::TcpListener::from_std(listener).unwrap();

    let handle = tokio::spawn(async move {
        loop {
            let Ok((mut stream, _)) = tokio_listener.accept().await else {
                break;
            };
            // Read the request (consume until \r\n\r\n)
            let mut buf = vec![0u8; 4096];
            let _ = tokio::io::AsyncReadExt::read(&mut stream, &mut buf).await;

            let response = format!(
                "HTTP/1.1 200 OK\r\nContent-Length: {}\r\nConnection: close\r\n\r\n",
                body.len()
            );
            let _ = stream.write_all(response.as_bytes()).await;
            let _ = stream.write_all(&body).await;
            let _ = stream.shutdown().await;
        }
    });

    (addr, handle)
}

#[tokio::test]
async fn test_ensure_plugin_cached_returns_path_when_binary_exists() {
    let dir = tempfile::tempdir().unwrap();
    let plugins_dir = dir.path().join("plugins");
    std::fs::create_dir_all(&plugins_dir).unwrap();

    let platform = platform_key();
    let binary_name = format!("test-plugin-1.0.0-{platform}");
    let cached_path = plugins_dir.join(&binary_name);

    // Manually place the test plugin binary into the cache location
    let source_binary = test_plugin_binary_path();
    std::fs::copy(&source_binary, &cached_path).unwrap();

    let config = PluginHostConfig {
        plugins_dir: plugins_dir.clone(),
        timeout_secs: 5,
        lock_file_path: Some(dir.path().join("yard.lock")),
    };

    // URL is bogus -- the binary is already cached so no HTTP request fires
    let result = ensure_plugin_cached(
        "test-plugin",
        "1.0.0",
        "http://bogus-should-not-be-called/${name}",
        &config,
    )
    .await;

    let path = result.unwrap();
    assert_eq!(path, cached_path, "should return the cached binary path");
    assert!(path.exists(), "cached binary should exist on disk");
}

#[tokio::test]
async fn test_ensure_plugin_cached_cache_miss_downloads() {
    let dir = tempfile::tempdir().unwrap();
    let plugins_dir = dir.path().join("plugins");
    std::fs::create_dir_all(&plugins_dir).unwrap();
    let lock_path = dir.path().join("yard.lock");

    // Read the test plugin binary content to serve over HTTP
    let source_binary = test_plugin_binary_path();
    let binary_bytes = std::fs::read(&source_binary).unwrap();

    let (addr, server_handle) = spawn_http_server(binary_bytes.clone());

    let config = PluginHostConfig {
        plugins_dir: plugins_dir.clone(),
        timeout_secs: 10,
        lock_file_path: Some(lock_path.clone()),
    };

    let url_template = format!("http://{addr}/${{name}}-${{version}}");
    let result = ensure_plugin_cached("test-plugin", "1.0.0", &url_template, &config).await;

    server_handle.abort();

    let path = result.unwrap();
    let platform = platform_key();
    let expected_name = format!("test-plugin-1.0.0-{platform}");
    assert_eq!(
        path.file_name().unwrap().to_str().unwrap(),
        expected_name,
        "downloaded binary should have the expected filename"
    );
    assert!(path.exists(), "downloaded binary should exist on disk");

    // Verify the binary content matches what the server served
    let downloaded = std::fs::read(&path).unwrap();
    assert_eq!(
        downloaded.len(),
        binary_bytes.len(),
        "downloaded binary size should match source"
    );

    // Verify the lock file was created with the correct entry
    assert!(lock_path.exists(), "lock file should exist after download");
    let lock_contents = std::fs::read_to_string(&lock_path).unwrap();
    let lock: LockFile = serde_json::from_str(&lock_contents).unwrap();
    assert_eq!(lock.plugins.len(), 1);
    assert_eq!(lock.plugins[0].name, "test-plugin");
    assert_eq!(lock.plugins[0].version, "1.0.0");
    assert!(
        lock.plugins[0].checksums.contains_key(&platform),
        "lock file should contain a checksum for the current platform"
    );
}

#[tokio::test]
async fn test_version_mismatch_triggers_redownload() {
    let dir = tempfile::tempdir().unwrap();
    let plugins_dir = dir.path().join("plugins");
    std::fs::create_dir_all(&plugins_dir).unwrap();
    let lock_path = dir.path().join("yard.lock");

    let platform = platform_key();
    let source_binary = test_plugin_binary_path();

    // Seed: place an old version binary in the cache
    let old_binary_name = format!("test-plugin-0.3.1-{platform}");
    let old_cached = plugins_dir.join(&old_binary_name);
    std::fs::copy(&source_binary, &old_cached).unwrap();

    // Seed a lock file with the old version
    update_lock_file(
        Some(&lock_path),
        "test-plugin",
        "0.3.1",
        &platform,
        "old_checksum_abc",
    )
    .await
    .unwrap();

    // Serve the binary for the new version download
    let binary_bytes = std::fs::read(&source_binary).unwrap();
    let (addr, server_handle) = spawn_http_server(binary_bytes);

    let config = PluginHostConfig {
        plugins_dir: plugins_dir.clone(),
        timeout_secs: 10,
        lock_file_path: Some(lock_path.clone()),
    };

    let url_template = format!("http://{addr}/${{name}}-${{version}}");
    let result = ensure_plugin_cached("test-plugin", "0.4.0", &url_template, &config).await;

    server_handle.abort();

    let path = result.unwrap();
    let new_binary_name = format!("test-plugin-0.4.0-{platform}");
    assert_eq!(
        path.file_name().unwrap().to_str().unwrap(),
        new_binary_name,
        "should download with the new version filename"
    );
    assert!(path.exists(), "new version binary should exist");
    assert!(
        old_cached.exists(),
        "old version binary should still exist (cleanup is future yard plugin clean)"
    );

    // Verify the lock file was updated with the new version
    let lock_contents = std::fs::read_to_string(&lock_path).unwrap();
    let lock: LockFile = serde_json::from_str(&lock_contents).unwrap();
    let entry = lock
        .plugins
        .iter()
        .find(|e| e.name == "test-plugin")
        .expect("lock file should have test-plugin entry");
    assert_eq!(entry.version, "0.4.0", "lock entry should have new version");
    assert!(
        entry.checksums.contains_key(&platform),
        "lock entry should have a checksum for the current platform"
    );
    // Old checksums are cleared on version bump (D-19)
    assert_eq!(
        entry.checksums.len(),
        1,
        "stale checksums should be cleared after version bump"
    );
}

#[tokio::test]
async fn test_update_lock_file_accumulates_platforms() {
    let dir = tempfile::tempdir().unwrap();
    let lock_path = dir.path().join("yard.lock");

    // Seed with one platform
    update_lock_file(
        Some(&lock_path),
        "test-plugin",
        "1.0.0",
        "x86_64-linux",
        "abc123",
    )
    .await
    .unwrap();

    // Add a second platform, same plugin and version
    update_lock_file(
        Some(&lock_path),
        "test-plugin",
        "1.0.0",
        "aarch64-macos",
        "def456",
    )
    .await
    .unwrap();

    let lock_contents = std::fs::read_to_string(&lock_path).unwrap();
    let lock: LockFile = serde_json::from_str(&lock_contents).unwrap();

    assert_eq!(lock.plugins.len(), 1, "should still be one plugin entry");
    let entry = &lock.plugins[0];
    assert_eq!(entry.name, "test-plugin");
    assert_eq!(entry.version, "1.0.0");
    assert_eq!(
        entry.checksums.len(),
        2,
        "should have two platform checksums"
    );
    assert_eq!(
        entry.checksums.get("x86_64-linux"),
        Some(&"abc123".to_string())
    );
    assert_eq!(
        entry.checksums.get("aarch64-macos"),
        Some(&"def456".to_string())
    );
}
