[package]
name = "yard-core"
version = "0.7.3"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
aws-config = { version = "1.8.15", features = ["behavior-version-latest"] }
aws-sdk-emr = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-glue = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-s3 = { version = "1.127.0", features = ["behavior-version-latest"] }
blake3 = { version = "1.8.3", features = ["serde"] }
chrono = "0.4.44"
regex = "1.12.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
tera = "1.20.1"
tokio = { version = "1.50.0", features = ["full"] }
walkdir = "2.5.0"
yaml-rust2 = "0.11.0"

yard-structs = { path = "../yard-structs" }
